<a href="https://colab.research.google.com/github/renegarcialuces/Analisis-de-Datos-Portafolio/blob/main/ED02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Variable objetivo**
Chun = Si el ciente canceló el sevicio. Esta es la variable a analizar

In [39]:
# Importar herramientas de analisis de datos
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
from scipy.stats import skew, describe

# **Carga de los datos**

In [40]:
# Cargar documentos para analisis desde la pc
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

# **Creación del DataFrame**

In [41]:
filename = '/content/drive/MyDrive/Tablas/telecom_users.csv'
df = pd.read_csv(filename, index_col=0) #[index_col= 0] Elimina la columna (Unnamed: 0).

# **Conociendo el datset**

In [42]:
# Qué columnas tiene el DataFrame?
df.columns

Index(['IDCliente', 'Genero', 'Aposentado', 'Casado', 'Dependentes',
       'MesesComoCliente', 'ServicoTelefone', 'MultiplasLinhas',
       'ServicoInternet', 'ServicoSegurancaOnline', 'ServicoBackupOnline',
       'ProtecaoEquipamento', 'ServicoSuporteTecnico', 'ServicoStreamingTV',
       'ServicoFilmes', 'TipoContrato', 'FaturaDigital', 'FormaPagamento',
       'ValorMensal', 'TotalGasto', 'Churn', 'Codigo'],
      dtype='object')

In [43]:
# De qué tamaños es el set de datos?
df.shape

(5986, 22)

In [44]:
# Tiene valores nulos o ausentes?
df.isna().sum()

IDCliente                    0
Genero                       0
Aposentado                   0
Casado                       0
Dependentes                  1
MesesComoCliente             0
ServicoTelefone              0
MultiplasLinhas              0
ServicoInternet              0
ServicoSegurancaOnline       0
ServicoBackupOnline          0
ProtecaoEquipamento          0
ServicoSuporteTecnico        0
ServicoStreamingTV           0
ServicoFilmes                0
TipoContrato                 0
FaturaDigital                0
FormaPagamento               0
ValorMensal                  0
TotalGasto                   0
Churn                        1
Codigo                    5986
dtype: int64

In [45]:
# Tipos de columnas?
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5986 entries, 1869 to 860
Data columns (total 22 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   IDCliente               5986 non-null   object
 1   Genero                  5986 non-null   object
 2   Aposentado              5986 non-null   int64
 3   Casado                  5986 non-null   object
 4   Dependentes             5985 non-null   object
 5   MesesComoCliente        5986 non-null   int64
 6   ServicoTelefone         5986 non-null   object
 7   MultiplasLinhas         5986 non-null   object
 8   ServicoInternet         5986 non-null   object
 9   ServicoSegurancaOnline  5986 non-null   object
 10  ServicoBackupOnline     5986 non-null   object
 11  ProtecaoEquipamento     5986 non-null   object
 12  ServicoSuporteTecnico   5986 non-null   object
 13  ServicoStreamingTV      5986 non-null   object
 14  ServicoFilmes           5986 non-null   object
 15  TipoContrato            5986 non-null   object
 16  FaturaDigital           5986 non-null   object
 17  FormaPagamento          5986 non-null   object
 18  ValorMensal             5986 non-null   float64
 19  TotalGasto              5986 non-null   object
 20  Churn                   5985 non-null   object
 21  Codigo                  0 non-null      float64
dtypes: float64(2), int64(2), object(18)
memory usage: 1.1+ MB

In [46]:
# Distribución estadística de las columnas numericas
df.describe()

        Aposentado  MesesComoCliente  ValorMensal  Codigo
count  5986.000000       5986.000000  5986.000000     0.0
mean      0.161377         32.468760    64.802213     NaN
std       0.367909         24.516391    30.114702     NaN
min       0.000000          0.000000    18.250000     NaN
25%       0.000000          9.000000    35.650000     NaN
50%       0.000000         29.000000    70.400000     NaN
75%       0.000000         56.000000    89.900000     NaN
max       1.000000         72.000000   118.750000     NaN

In [47]:
# Distribución estadística de las columnas categóricas
df.describe(exclude=['int', 'float'])

,IDCliente,Genero,Casado,Dependentes,ServicoTelefone,MultiplasLinhas,ServicoInternet,ServicoSegurancaOnline,ServicoBackupOnline,ProtecaoEquipamento,ServicoSuporteTecnico,ServicoStreamingTV,ServicoFilmes,TipoContrato,FaturaDigital,FormaPagamento,TotalGasto,Churn
count,5986,5986,5986,5985,5986,5986,5986,5986,5986,5986,5986,5986,5986,5986,5986,5986,5986,5985
unique,5986,2,2,2,2,3,3,3,3,3,3,3,3,3,2,4,5611,2
top,4795-UXVCJ,Masculino,Nao,Nao,Sim,Nao,Fibra,Nao,Nao,Nao,Nao,Nao,Nao,Mensal,Sim,BoletoEletronico,,Nao
freq,1,3050,3082,4195,5396,2848,2627,2982,2605,2640,2960,2389,2356,3269,3528,2006,10,4398

# **Limpieza y preparación de datos**

In [48]:
# Ajuster tipo de categórico a numerico
df['TotalGasto'] = pd.to_numeric(df['TotalGasto'], errors='coerce')

In [49]:
# Covertir columnas numericas a categoricos
df['Aposentado'] = df['Aposentado'].astype('category')
df['Aposentado'] = df['Aposentado'].map({1: 'Sim', 0: 'Não'})

In [50]:
# Covertir columnas objectos a categoricos
for col in df.columns:
  if df[col].dtypes == 'O':
    df[col] = df[col].astype('category')

In [51]:
# Borrando columnas vacia
df.dropna(axis=1, how='all', inplace=True)

In [52]:
# Borras datos faltantes
df.dropna(how='any', inplace=True)

# **Tablas de frecuencia y gráficos**

In [53]:
for columna in df:
  if columna not in ['IDCliente', 'TotalGasto', 'Churn', 'Codigo']:
    fig = px.histogram(df, x=columna, color='Churn')
    fig.show()
    display(df.pivot_table(index='Churn', columns=columna, values='IDCliente', aggfunc='count'))

/tmp/ipykernel_10494/2539282060.py:5: FutureWarning:

The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior

Genero  Feminino  Masculino
Churn
Nao         2140       2247
Sim          791        796

/tmp/ipykernel_10494/2539282060.py:5: FutureWarning:

The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior

Aposentado   Não  Sim
Churn
Nao         3823  564
Sim         1185  402

/tmp/ipykernel_10494/2539282060.py:5: FutureWarning:

The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior

Casado   Nao   Sim
Churn
Nao     2069  2318
Sim     1011   576

/tmp/ipykernel_10494/2539282060.py:5: FutureWarning:

The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior

Dependentes   Nao   Sim
Churn
Nao          2888  1499
Sim          1306   281

/tmp/ipykernel_10494/2539282060.py:5: FutureWarning:

The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior

MesesComoCliente,1,2,3,4,5,6,7,8,9,10,...,63,64,65,66,67,68,69,70,71,72
Churn,,,,,,,,,,,,,,,,,,,,,
Nao,192,90,87,81,59,62,70,73,60,63,...,60,68,56,63,73,81,69,80,147,304
Sim,318,104,82,73,52,36,41,37,37,39,...,2,3,9,11,8,8,6,10,5,4

/tmp/ipykernel_10494/2539282060.py:5: FutureWarning:

The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior

ServicoTelefone  Nao   Sim
Churn
Nao              439  3948
Sim              149  1438

/tmp/ipykernel_10494/2539282060.py:5: FutureWarning:

The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior

MultiplasLinhas   Nao  SemTelefone   Sim
Churn
Nao              2127          439  1821
Sim               715          149   723

/tmp/ipykernel_10494/2539282060.py:5: FutureWarning:

The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior

ServicoInternet   DSL  Fibra   Nao
Churn
Nao              1666   1536  1185
Sim               397   1091    99

/tmp/ipykernel_10494/2539282060.py:5: FutureWarning:

The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior

ServicoSegurancaOnline   Nao  SemInternet   Sim
Churn
Nao                     1740         1185  1462
Sim                     1242           99   246

/tmp/ipykernel_10494/2539282060.py:5: FutureWarning:

The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior

ServicoBackupOnline   Nao  SemInternet   Sim
Churn
Nao                  1566         1185  1636
Sim                  1038           99   450

/tmp/ipykernel_10494/2539282060.py:5: FutureWarning:

The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior

ProtecaoEquipamento   Nao  SemInternet   Sim
Churn
Nao                  1608         1185  1594
Sim                  1031           99   457

/tmp/ipykernel_10494/2539282060.py:5: FutureWarning:

The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior

ServicoSuporteTecnico   Nao  SemInternet   Sim
Churn
Nao                    1737         1185  1465
Sim                    1222           99   266

/tmp/ipykernel_10494/2539282060.py:5: FutureWarning:

The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior

ServicoStreamingTV   Nao  SemInternet   Sim
Churn
Nao                 1589         1185  1613
Sim                  799           99   689

/tmp/ipykernel_10494/2539282060.py:5: FutureWarning:

The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior

ServicoFilmes   Nao  SemInternet   Sim
Churn
Nao            1561         1185  1641
Sim             792           99   696

/tmp/ipykernel_10494/2539282060.py:5: FutureWarning:

The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior

TipoContrato  2 anos  Anual  Mensal
Churn
Nao             1389   1127    1871
Sim               41    148    1398

/tmp/ipykernel_10494/2539282060.py:5: FutureWarning:

The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior

FaturaDigital   Nao   Sim
Churn
Nao            2045  2342
Sim             406  1181

/tmp/ipykernel_10494/2539282060.py:5: FutureWarning:

The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior

FormaPagamento,BoletoEletronico,BoletoImpresso,CartaoCredito,DebitoAutomatico
Churn,,,,
Nao,1104,1098,1104,1081
Sim,902,263,198,224

/tmp/ipykernel_10494/2539282060.py:5: FutureWarning:

The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior

ValorMensal,18.25,18.40,18.55,18.70,18.75,18.80,18.85,18.90,18.95,19.00,...,117.15,117.35,117.45,117.60,117.80,118.20,118.35,118.60,118.65,118.75
Churn,,,,,,,,,,,,,,,,,,,,,
Nao,1,1,1,1,1,6,3,2,4,6,...,1,1,0,1,0,1,0,2,1,1
Sim,0,0,0,0,0,0,1,0,1,1,...,0,0,1,0,1,0,1,0,0,0